language: java

jdk:
  - oraclejdk8
  
sudo: false

before_install:
  - mvn checkstyle:check
  
script: "mvn cobertura:cobertura"
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: never